# Generated by Django 2.0.2 on 2018-12-02 12:17

import datetime
from django.db import migrations, models
import enumfields.fields
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start time')),
                ('exec_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Execution time')),
                ('status', enumfields.fields.EnumField(enum=task.models.Status, max_length=1)),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ('-create_time', '-status'),
            },
        ),
    ]
